version: '3'
services:
  myapp:
    image: spring-demo-app
    restart: always
    build: .
    container_name: myapp
    ports:
      - 8080:8080
    environment:
      MYSQL_HOST: mysql8
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306

  mysql:
    container_name: mysql8
    image: mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: root