version: '3'
services:
  mysql:
    build: docker/mysql
    container_name: mysql8
    ports:
      - "3307:3306"
  myapp:
    build: docker/app
    container_name: myapp
    ports:
      - "8080:8080"
